### PR TITLE
Add additional poplinks for decks

### PR DESCRIPTION
**Pull request by jonasdn**
- Add poplink for Active Marker Deck
- Add poplink for Motion capture marker deck

### CODE REVIEW

**Comment by knmcguire** [comment]
Thanks! I'll be adding some additional commits for consistency!

**Comment by knmcguire** [comment]
Just pushed some commits

- There ware some link issues in the markdown of the pop-links, so some URL referrals failed
- I just added and removed pop links in places so that it was more consistency on where the others were placed. 
- The blogpost I've removed about the active marker deck, as we don't do this in other poplinks, however might be an idea for #93 to add this to the product page?

if this looks good to you, then let's merge and deploy the web tomorrow

**Review by jonasdn — COMMENTED** [review]
:1st_place_medal:

**Comment by knmcguire** [comment]
awesome ! let's merge it

**Pull request merged**
