### PR TITLE
Add serial port config for linux in LH docs

### PR DESCRIPTION
**Pull request by jonasdn**
perms

### CODE REVIEW

**Comment by knmcguire** [comment]
Since this is OS based, could we perhaps make some tabs groups? Like here: https://www.bitcraze.io/documentation/tutorials/getting-started-with-crazyflie-2-x/#inst-comp
For Linux we can say that there are extra things that are required, but for windows (and mac??) no further action is required, accept for double checking the device manager?

Just checking for consistency with the other tutorials

**Comment by jonasdn** [comment]
> Since this is OS based, could we perhaps make some tabs groups? Like here: https://www.bitcraze.io/documentation/tutorials/getting-started-with-crazyflie-2-x/#inst-comp
> For Linux we can say that there are extra things that are required, but for windows (and mac??) no further action is required, accept for double checking the device manager?
> 
> Just checking for consistency with the other tutorials

Thanks! Will attempt to fix this!

**Comment by jonasdn** [comment]
I do not really know what to write for non-Linux, any ideas? Or just have the one tab?

**Comment by knmcguire** [comment]
Maybe just one tab for now yeah. Unless we are completely sure about the others

**Pull request merged**
