### PR TITLE
Update research.md

### PR DESCRIPTION
**Pull request by OmarShadeed**

### CODE REVIEW

**Comment by ataffanel** [comment]
Thanks a lot, I merge it.

**Comment by OmarShadeed** [comment]
Hi, 
It's not reflected on the website yet. Does it usually take that long or I did smth wrong?
Thanks.

**Comment by krichardsson** [comment]
Hi!
Your change has not been deployed to the production server yet and this is why you can not see it. It will probably be deployed tomorrow.

**Comment by OmarShadeed** [comment]
Alright.  Thanks

**Pull request merged**
